// Package promptversion is the central registry of prompt versions per content
// kind. Bump a kind's version whenever its generation prompt changes materially,
// so the release metadata records which prompt produced each artifact and prompt
// evolution is auditable ("blog produced by blog@6, later regenerated by blog@7").
//
// Versions are formatted "<kind>@<n>". Kinds not listed default to "<kind>@1".
package promptversion

import "fmt"

// versions maps a content kind to its current prompt revision. Increment when a
// generator's prompt changes in a way that alters output character.
var versions = map[string]int{
	// Claude-written, prompt-heavy artifacts.
	"blog":                      15, // Rotating narrative archetypes + story-driven headings + grounded first-person voice; forbid the generic template headings (Why This Matters/The Solution/Benefits/Conclusion)
	"architecture":              2,
	"linkedin":                  2,
	"x-thread":                  2,
	"architecture-diagram-spec": 1,
	// model transforms + deterministic artifacts.
	"storyboard": 2, // narrative arc: opening scene orients on the capability (what the system does, never "this release"/version/repo) before the hook; LAST scene always lands a grounded close/CTA; evergreen — narration never references the release/version/repository
	// The storyboard-consuming stages are bumped in lockstep with storyboard@2: they
	// carry the scene narration, so their produced content changes with the new arc.
	// (The suite has no upstream→downstream staleness cascade, so an idempotent
	// re-run only refreshes a stage when its OWN version changes.)
	"voiceover":      2,
	"youtube":        2,
	"youtube-shorts": 2,
	"tiktok":         2,
	"visual-assets":  2, // SDXL-first: shared style+negative anchors, per-category Replicate stability-ai/sdxl params, rotating composition archetypes, machine-readable release_context + collection_intelligence + AI generation rules
	"seo-metadata":   1,
	// Deterministic renderer (no model prompt), versioned for parity.
	"architecture-diagram": 1,
	"storyboard-scenes":    2, // deterministic per-scene SDXL image specs derived from the storyboard (bumped with storyboard@2: narration-alignment fields change)
}

// For returns the prompt version string for a content kind (e.g. "blog@6").
// Unregistered kinds default to revision 1.
func For(kind string) string {
	n := versions[kind]
	if n == 0 {
		n = 1
	}
	return fmt.Sprintf("%s@%d", kind, n)
}
