// Package promptversion is the central registry of prompt versions per content
// kind. Bump a kind's version whenever its generation prompt changes materially,
// so the release metadata records which prompt produced each artifact and prompt
// evolution is auditable ("blog produced by blog@6, later regenerated by blog@7").
//
// Versions are formatted "<kind>@<n>". Kinds not listed default to "<kind>@1".
package promptversion

import "fmt"

// versions maps a content kind to its current prompt revision. Increment when a
// generator's prompt changes in a way that alters output character.
var versions = map[string]int{
	// Claude-written, prompt-heavy artifacts.
	"blog":                      14, // Tradeoffs must cover the ongoing cost of pre-baked images (snapshot storage growth, rebuild cadence, patching) for baked-image releases
	"architecture":              2,
	"linkedin":                  2,
	"x-thread":                  2,
	"architecture-diagram-spec": 1,
	// model transforms + deterministic artifacts.
	"storyboard":     1,
	"voiceover":      1,
	"youtube":        1,
	"youtube-shorts": 1,
	"tiktok":         1,
	"visual-assets":  1,
	"seo-metadata":   1,
	// Deterministic renderer (no model prompt), versioned for parity.
	"architecture-diagram": 1,
}

// For returns the prompt version string for a content kind (e.g. "blog@6").
// Unregistered kinds default to revision 1.
func For(kind string) string {
	n := versions[kind]
	if n == 0 {
		n = 1
	}
	return fmt.Sprintf("%s@%d", kind, n)
}
