package airouter

import (
	"encoding/json"
	"fmt"
	"strings"
)

// Provider names used by the default policy and the worker wiring.
const (
	ProviderClaude = "claude"
	ProviderOllama = "ollama"
)

// AllKinds is the set of content kinds the suite can produce, in generation
// order. It matches the orchestrator's stage names and is the vocabulary the
// routing rules key off.
var AllKinds = []string{
	"blog", "storyboard", "voiceover", "architecture", "youtube",
	"youtube-shorts", "tiktok", "visual-assets", "seo-metadata",
	"linkedin", "x-thread", "architecture-diagram-spec",
}

// DefaultRules is the recommended hybrid policy: premium model for the
// high-value, public-facing writing; everything else defaults to the cheap
// local model via the router's default provider. Kinds not listed here fall to
// the default provider, so this map stays small and intent-revealing.
func DefaultRules() map[string]string {
	return map[string]string{
		"blog":                      ProviderClaude, // flagship long-form article
		"architecture":              ProviderClaude, // technical reasoning + trade-offs
		"linkedin":                  ProviderClaude, // professional public communication
		"x-thread":                  ProviderClaude, // audience engagement
		"architecture-diagram-spec": ProviderClaude, // AWS diagram design (engineering, not rendering)
		"storyboard":                ProviderClaude, // spoken voice-over script — public-facing writing; the small model produces autogenerated-sounding, sometimes inaccurate narration
		// voiceover, youtube, youtube-shorts, tiktok, visual-assets,
		// seo-metadata → default provider (Ollama): structured / repetitive / cheap.
	}
}

// aliases maps convenient short names to canonical stage names, so a config may
// say "seo" or "shorts" and still route correctly.
var aliases = map[string]string{
	"seo":          "seo-metadata",
	"seometadata":  "seo-metadata",
	"shorts":       "youtube-shorts",
	"yt-shorts":    "youtube-shorts",
	"xthread":      "x-thread",
	"x":            "x-thread",
	"twitter":      "x-thread",
	"visuals":      "visual-assets",
	"visualassets": "visual-assets",
	"arch":         "architecture",
	"yt":           "youtube",
}

// canonical normalises a kind name (case, spacing, aliases) to a stage name.
func canonical(kind string) string {
	k := strings.ToLower(strings.TrimSpace(kind))
	k = strings.ReplaceAll(k, "_", "-")
	k = strings.ReplaceAll(k, " ", "-")
	if c, ok := aliases[strings.ReplaceAll(k, "-", "")]; ok {
		return c
	}
	if c, ok := aliases[k]; ok {
		return c
	}
	return k
}

// ParseRules parses a routing config into a kind->provider map. It accepts a
// JSON form and a shell-safe compact form:
//
//	{"claude": ["blog","architecture"], "ollama": ["seo-metadata"]}   (JSON: provider -> kinds)
//	{"blog": "claude", "seo-metadata": "ollama"}                       (JSON: kind -> provider)
//	claude=blog,architecture;ollama=seo-metadata,tiktok               (compact: provider=kinds; …)
//
// The compact form has no quotes, spaces, or braces, so it survives being passed
// as a GitHub repo variable → CloudFormation parameter → systemd EnvironmentFile
// without escaping. An empty string yields the DefaultRules.
func ParseRules(s string) (map[string]string, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return DefaultRules(), nil
	}
	if !strings.HasPrefix(s, "{") {
		return parseCompact(s)
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal([]byte(s), &raw); err != nil {
		return nil, fmt.Errorf("airouter: parse routing config: %w", err)
	}
	out := make(map[string]string)
	for key, val := range raw {
		// Try provider -> [kinds] first.
		var kinds []string
		if err := json.Unmarshal(val, &kinds); err == nil {
			provider := strings.ToLower(strings.TrimSpace(key))
			for _, k := range kinds {
				out[canonical(k)] = provider
			}
			continue
		}
		// Else kind -> provider.
		var provider string
		if err := json.Unmarshal(val, &provider); err == nil {
			out[canonical(key)] = strings.ToLower(strings.TrimSpace(provider))
			continue
		}
		return nil, fmt.Errorf("airouter: routing entry %q is neither a provider list nor a provider name", key)
	}
	return out, nil
}

// parseCompact parses the shell-safe form "provider=kind,kind;provider=kind".
func parseCompact(s string) (map[string]string, error) {
	out := make(map[string]string)
	for _, group := range strings.Split(s, ";") {
		group = strings.TrimSpace(group)
		if group == "" {
			continue
		}
		provider, kinds, ok := strings.Cut(group, "=")
		if !ok {
			return nil, fmt.Errorf("airouter: routing group %q must be provider=kinds", group)
		}
		provider = strings.ToLower(strings.TrimSpace(provider))
		if provider == "" {
			return nil, fmt.Errorf("airouter: routing group %q has an empty provider", group)
		}
		for _, k := range strings.Split(kinds, ",") {
			if k = strings.TrimSpace(k); k != "" {
				out[canonical(k)] = provider
			}
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("airouter: no routing rules parsed from %q", s)
	}
	return out, nil
}
